# Generated by Django 5.1.3 on 2025-04-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "game_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="game_images/"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("max_players", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "playcanvas_project_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FootballRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("room_code", models.CharField(max_length=10, unique=True)),
                (
                    "game_type",
                    models.CharField(
                        choices=[("3v3", "3v3"), ("5v5", "5v5"), ("6v6", "6v6")],
                        default="6v6",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Not Started",
                        max_length=15,
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("password", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_football_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="football_room_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FootballPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Team A"), ("B", "Team B")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GK", "Goalkeeper"),
                            ("DEF", "Defender"),
                            ("MID", "Midfielder"),
                            ("FWD", "Forward"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("x_position", models.FloatField(default=0.0)),
                ("y_position", models.FloatField(default=0.0)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("score", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="football_player_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="games.footballroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FootballMatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_a_score", models.PositiveIntegerField(default=0)),
                ("team_b_score", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_score",
                        to="games.footballroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FootballBall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x_position", models.FloatField(default=50.0)),
                ("y_position", models.FloatField(default=50.0)),
                ("radius", models.FloatField(default=5.0)),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="football_ball",
                        to="games.footballroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        blank=True, editable=False, max_length=10, unique=True
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                (
                    "is_started",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Not Started",
                        max_length=15,
                    ),
                ),
                ("max_players", models.PositiveIntegerField(default=4)),
                ("is_active", models.BooleanField(default=True)),
                ("is_starting", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="game_rooms", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.gameroom"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="games.footballplayer",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="games.footballroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.IntegerField(default=1)),
                ("body_positions", models.JSONField(default=list)),
                ("direction", models.CharField(default="up", max_length=10)),
                ("color", models.CharField(default="green", max_length=20)),
                ("is_alive", models.BooleanField(default=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "game_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.gameroom"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("current_position", models.JSONField(default=dict)),
                ("is_ready", models.BooleanField(default=False)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "game_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.gameroom"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "game_room")},
            },
        ),
    ]
