# Generated by Django 5.1.3 on 2024-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
