# Generated by Django 5.1.3 on 2025-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_newmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatus",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
