# Generated by Django 5.1.3 on 2024-12-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_remove_playerstatus_is_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstatus",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
