# Generated by Django 5.1.3 on 2024-12-06 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_playerstatus_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Snake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("length", models.IntegerField(default=1)),
                ("body_positions", models.JSONField(default=list)),
                ("direction", models.CharField(default="up", max_length=10)),
                ("color", models.CharField(default="green", max_length=20)),
                ("is_alive", models.BooleanField(default=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "game_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.gameroom"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
