# Generated by Django 5.1.3 on 2025-03-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_game_playcanvas_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
